from typing import Optional, Union

from typer import FileBinaryRead

from pythonanywhere_core.files import Files


class PAPath:
    path: str = ...
    api: Files = ...
    def __init__(self, path: str) -> None: ...
    def __repr__(self) -> str: ...
    def _make_sharing_url(self, path: str) -> str: ...
    @staticmethod
    def _standarize_path(path: str) -> str: ...
    @property
    def url(self) -> str: ...
    @property
    def contents(self) -> Optional[Union[dict, str]]: ...
    @property
    def tree(self) -> Optional[list]: ...
    def delete(self) -> bool: ...
    def upload(self, content: FileBinaryRead) -> bool: ...
    def get_sharing_url(self) -> str: ...
    def share(self) -> str: ...
    def unshare(self) -> bool: ...
