from typing import List, Optional, Union

from typing_extensions import Literal

class PAPath:
    def __init__(self, path: str) -> None: ...
    def __repr__(self) -> str: ...
    def contents(self) -> Union[dict, str]: ...
    def delete(self) -> bool: ...
    def upload(self, content: bytes) -> bool: ...
    def get_sharing_url(self) -> str: ...
    def share(self) -> str: ...
    def unshare(self) -> bool: ...
