from pathlib import Path

from pythonanywhere_core.webapp import Webapp

from pythonanywhere.virtualenvs import Virtualenv

class Project:
    domain: str = ...
    python_version: str = ...
    project_path: Path = ...
    virtualenv: Virtualenv = ...
    wsgi_file_path: Path = ...
    webapp: Webapp = ...
    def __init__(self, domain: str, python_version: str) -> None: ...
    def sanity_checks(self, nuke: bool) -> None: ...
    def create_webapp(self, nuke: bool) -> None: ...
    def add_static_file_mappings(self) -> None: ...
    def reload_webapp(self) -> None: ...
    def start_bash(self) -> None: ...
