from typing import Type, Tuple, List, Iterator

MESSAGE = Type[str]

def snakesay(*things) -> str: ...
def speech_bubble_lines(speech: str) -> Iterator[str]: ...
def rewrap(speech: str) -> Tuple[List[str], int]: ...
