from typing import Optional
from pythonanywhere.api.students_api import Students_Api

class Students:
    api: StudentsAPI = ...
    def __init__(self) -> None: ...
    def get(self) -> Optional[list]: ...
    def delete(self, username: str) -> bool: ...
