from typing import Dict

from requests import Response

PYTHON_VERSIONS: Dict[str, str] = ...

class AuthenticationError(Exception): ...
class NoTokenError(Exception): ...

def get_api_endpoint() -> str: ...
def call_api(url: str, method: str, **kwargs) -> Response: ...


