from requests.models import Response
from typing import Tuple, Union

class Files:
    base_url: str = ...
    path_endpoint: str = ...
    sharing_endpoint: str = ...
    tree_endpoint: str = ...

    def _error_msg(self, result: Response) -> str: ...
    def path_get(self, path: str) -> Union[dict, bytes]: ...
    def path_post(self, dest_path: str, source: bytes) -> int: ...
    def path_delete(self, path: str) -> int: ...
    def sharing_post(self, path: str) -> Tuple[int, str]: ...
    def sharing_get(self, path: str) -> str: ...
    def sharing_delete(self, path: str) -> int: ...
    def tree_get(self, path: str) -> dict: ...
